### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by ctrl** [consultiaio/mediatize#1]
Stack; EC2, nginx/1.8.0, php-fpm MySQL.

Just need some assistance with the rewrite. nginx file look like? 
And if you're not using nginx, then, what does your configuration look like? Thanks!

**Comment by nosuko** [comment]
Hi! Nginx it's mandatory. The code it's designed to work with nginx.
This is a forked project, but the original programmer post this info:
https://groups.google.com/d/msg/meneame/xdO-0I27DeM/XR3nLcylDRwJ
The entire google group it's interesting because many questions are answered there.
Regards!
